server:
  port: 1112
eureka:
  instance:
    hostname: peer2
    appname: server
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://peer1:1111/eureka/
spring:
  application:
    name: server
